project_identifier: jce-mediabox
api_key: 
base_path: 
base_url: 
preserve_hierarchy: true
files:
  - source: en-GB.plg_system_jcemediabox*.ini
    translation: '%locale%.%original_file_name%'
    translation_replace:
      en-GB.: 
    type: ini
  - source: en-GB.jcemediabox.xml
    translation: '%locale%.%original_file_name%'
    translation_replace:
      en-GB.: 
    type: xml
